version: '3.7'
services:
  strapi:
    build:
      dockerfile: Dockerfile.staging
      context: .
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    ports:
      - 1337:1337
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - FIREBASE_AUTH_PROJECT_ID=${FIREBASE_AUTH_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_AUTH_DATABASE_URL=${FIREBASE_AUTH_DATABASE_URL}
volumes:
  node_modules:
